version: "3.6"

services:
  api:
    image: iam4x/bobarr-api:latest
    command: yarn start:prod
    restart: unless-stopped

  web:
    image: iam4x/bobarr-web:latest
    command: yarn start
    restart: unless-stopped
