version: "3.6"

services:
  vpn:
    image: bubuntux/nordvpn
    container_name: bobarr-nordlynx
    env_file: nordvpn.env
    network_mode: bridge
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    ports:
      - 9117:9117
      - 9091:9091
      - 3000:3000
      - 4000:4000
      - 80:80
    restart: always
  
  api:
    links:
      - vpn:transmission
    networks:
      - default

  transmission:
    network_mode: "service:vpn"
    depends_on:
      - vpn  