version: "3.6"

volumes:
  db_data:
  redis_data:

networks:
  default:

services:
  api:
    container_name: bobarr-api
    build:
      context: ./packages/api
    env_file: .env
    volumes:
      - ./library:/usr/library
    ports:
      - 4000:4000
    command: yarn start:prod
    restart: unless-stopped

  web:
    container_name: bobarr-web
    build:
      context: ./packages/web
    env_file: .env
    ports:
      - 3000:3000
    command: yarn start
    restart: unless-stopped

  postgres:
    container_name: bobarr-postgresql
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  redis:
    container_name: bobarr-redis
    image: bitnami/redis:5.0.6
    ports:
      - 6379:6379
    env_file: .env
    restart: unless-stopped
    volumes:
      - redis_data:/bitnami/redis/data

  jackett:
    image: linuxserver/jackett
    container_name: bobarr-jacket
    env_file: .env
    volumes:
      - ./packages/jackett/config:/config
      - ./packages/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  vpn:
    image: dperson/openvpn-client
    container_name: bobarr-vpn
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /dev/net:/dev/net:z
      - ./packages/vpn:/vpn
    entrypoint: "bash -c"
    command: "exit 0"

  transmission:
    image: linuxserver/transmission
    container_name: bobarr-transmission
    env_file: .env
    volumes:
      - ./library/downloads:/downloads
      - ./packages/transmission/config:/config
      - ./packages/transmission/watch:/watch

  transmission-web:
    image: dperson/nginx
    container_name: bobarr-transmission-web
    depends_on:
      - transmission
    environment:
      - TZ=Europe/Paris
    ports:
      - "9091:80"
    command: -w "http://transmission:9091;/"
    restart: unless-stopped
